name: Test & Build  #pipeline name

on:
    push:
        branches:
            - main
        paths:
            - '**/*'    # all code

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # setup environment
            - name: checkout code  # to checkout and pull code from github
              uses: actions/checkout@v2

            - name: setup python  # to setup python
              uses: actions/setup-python@v2
              with:
                python-version: '3.9'

            - name: Docker Setup  # to setup docker
              uses: docker/setup-buildx-action@v2

            # install pip, requirement.txt all dependies, flask8 (used for testing purpose)
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip     
                pip install -r requirements.txt
                pip install flake8  

             # testing & linting(linting means code quality checks and syntax errors)
            - name: Run tests
              run: |     # ( | (pipe symbol) is used to run multiple commands) & --ignore=E501 is to ignore spaces in code.
                flake8 --ignore=E501,F401 .

            - name: Docker credentials
              uses: docker/login-action@v2
              with: 
                username: ${{   secrets.DOCKER_USERNAME  }}
                password: ${{   secrets.DOCKER_PASSWORD  }}

            - name: Docker tag
              id: version
              run: |
                 VERSION = v$(date + "%Y%m%d%H%M%S")
                 echo "VERSION::$VERSION" >> $GITHUB_ENV

            # Build docker image
            - name: Build Docker Image
              run: |
                 docker build . -t yashisrani05/demo-app:${{env.VERSION}}

            # Build docker image
            - name: Push Docker Image
              run: |
                 docker push yashisrani05/demo-app:${{env.VERSION}}




